import type { AccountSummary, CancelPreview, DashboardPayload, EnrichedTradeCandidate, Instrument, OrderDraft, OrderExecutionResult, OrderPreview, Position, TradeCandidate, TradePlanPayload, TradingEnvironment } from "../shared/contracts.js";
import { credentialStatus, type RuntimeConfig } from "./config.js";
import type { StateStore } from "./state-store.js";
import { ExecutionStatusUnknownError, Trading212Client } from "./trading212-client.js";
import { randomToken } from "./web-utils.js";

type Audit = (event: string, details: Record<string, unknown>) => Promise<void>;
type Pending = { kind: "order"; draft: OrderDraft } | { kind: "cancel"; environment: TradingEnvironment; orderId: string };
export interface InstrumentCacheEntry { expiresAt: number; instruments: Instrument[] }
export type InstrumentCache = Map<TradingEnvironment, InstrumentCacheEntry>;
export interface TradingServiceDeps { config: RuntimeConfig; store: StateStore; audit?: Audit; fetcher?: typeof fetch; instrumentCache?: InstrumentCache }

export function resolveInstrumentFromList(instruments: Instrument[], query: string): Instrument {
  const norm = (v: string) => v.trim().toUpperCase(), q = norm(query); if (!q) throw new Error("Ticker/symbol is required");
  const exact = instruments.find((x) => norm(x.ticker) === q); if (exact) return exact;
  const symbols = instruments.filter((x) => { const t = norm(x.ticker); return norm(x.shortName ?? "") === q || t.startsWith(`${q}_`) || t.startsWith(`${q}-`); });
  if (symbols.length === 1) return symbols[0]!;
  if (symbols.length > 1) { const us = symbols.find((x) => /_US_EQ$/i.test(x.ticker)); if (us) return us; const usd = symbols.filter((x) => norm(x.currencyCode) === "USD"); if (usd.length === 1) return usd[0]!; throw new Error(`Symbol ${query} is ambiguous. Use an exact Trading 212 ticker: ${symbols.slice(0, 8).map((x) => x.ticker).join(", ")}`); }
  const names = instruments.filter((x) => `${x.name ?? ""} ${x.shortName ?? ""}`.toUpperCase().includes(q));
  if (names.length === 1) return names[0]!; if (names.length > 1) throw new Error(`Instrument ${query} is ambiguous. Use an exact ticker: ${names.slice(0, 8).map((x) => x.ticker).join(", ")}`);
  throw new Error(`No Trading 212 instrument matched ${query}`);
}

export function validateOrderAgainstSnapshot(draft: OrderDraft, instrument: Instrument, position: Position | undefined, account: AccountSummary, config: Pick<RuntimeConfig, "maxOrderNotional" | "maxOrderQuantity">) {
  function positive(name: string, value?: number): asserts value is number { if (value === undefined || !Number.isFinite(value) || value <= 0) throw new Error(`${name} must be a positive number`); }
  if (!draft.ticker.trim()) throw new Error("Ticker is required"); positive("quantity", draft.quantity);
  if (draft.quantity > config.maxOrderQuantity) throw new Error(`Quantity exceeds MAX_ORDER_QUANTITY (${config.maxOrderQuantity})`);
  if (["limit", "stop_limit"].includes(draft.type)) positive("limitPrice", draft.limitPrice);
  if (["stop", "stop_limit"].includes(draft.type)) positive("stopPrice", draft.stopPrice);
  if (draft.extendedHours && draft.type !== "market") throw new Error("extendedHours is only supported for Market orders by the Trading 212 Public API");
  if (draft.extendedHours && !instrument.extendedHours) throw new Error(`${instrument.ticker} does not support extended-hours execution`);
  if (draft.side === "buy" && instrument.maxOpenQuantity && Math.max(0, position?.quantity ?? 0) + draft.quantity > instrument.maxOpenQuantity + Number.EPSILON) throw new Error(`Resulting quantity exceeds Trading 212 maxOpenQuantity (${instrument.maxOpenQuantity})`);
  if (draft.side === "sell" && draft.quantity > (position?.quantityAvailableForTrading ?? 0) + Number.EPSILON) throw new Error(`Sell quantity ${draft.quantity} exceeds available quantity ${position?.quantityAvailableForTrading ?? 0}`);
  const price = draft.type === "limit" || draft.type === "stop_limit" ? draft.limitPrice : draft.type === "stop" ? draft.stopPrice : draft.referencePrice ?? position?.currentPrice;
  if (!price || price <= 0) throw new Error("A current referencePrice is required for this Market order so the server can enforce the hard notional cap before submission");
  const estimatedNotional = price * draft.quantity; if (!Number.isFinite(estimatedNotional) || estimatedNotional <= 0) throw new Error("Estimated order notional is invalid");
  if (estimatedNotional > config.maxOrderNotional) throw new Error(`Estimated order notional ${estimatedNotional.toFixed(2)} ${instrument.currencyCode} exceeds MAX_ORDER_NOTIONAL (${config.maxOrderNotional})`);
  const availableCash = account.cash?.availableToTrade, sameCurrency = !!account.currency && account.currency.toUpperCase() === instrument.currencyCode.toUpperCase();
  if (draft.side === "buy" && sameCurrency && availableCash !== undefined && estimatedNotional > availableCash) throw new Error(`Estimated order notional ${estimatedNotional.toFixed(2)} exceeds available cash ${availableCash.toFixed(2)} ${account.currency}`);
  return { estimatedNotional, estimatedNotionalCurrency: instrument.currencyCode, cashCheckApplied: draft.side !== "buy" || sameCurrency, ...(availableCash === undefined ? {} : { availableCash }), ...(account.currency ? { accountCurrency: account.currency } : {}) };
}

export class TradingService {
  private readonly cache: InstrumentCache;
  constructor(private readonly deps: TradingServiceDeps) { this.cache = deps.instrumentCache ?? new Map(); }
  private client(e: TradingEnvironment) { return new Trading212Client(e, this.deps.config, this.deps.fetcher); }
  private async instruments(e: TradingEnvironment) { const c = this.cache.get(e); if (c && c.expiresAt > Date.now()) return c.instruments; const instruments = await this.client(e).getInstruments(); this.cache.set(e, { instruments, expiresAt: Date.now() + 600_000 }); return instruments; }
  private positionFor(p: Position[], ticker: string) { return p.find((x) => x.instrument?.ticker.toUpperCase() === ticker.toUpperCase()); }
  async searchInstruments(e: TradingEnvironment, query: string, limit = 20) { if (!credentialStatus(this.deps.config)[e]) return []; const q = query.trim().toUpperCase(); return (await this.instruments(e)).filter((x) => !q || `${x.ticker} ${x.shortName} ${x.name} ${x.isin ?? ""}`.toUpperCase().includes(q)).slice(0, limit); }
  async getDashboard(e: TradingEnvironment): Promise<DashboardPayload> { const credentials = credentialStatus(this.deps.config); if (!credentials[e]) return { kind: "portfolio", appName: "TradePilot 212", environment: e, credentials, account: null, positions: [], orders: [], timestamp: new Date().toISOString(), warning: `${e.toUpperCase()} credentials are not configured` }; const c = this.client(e); const [account, positions, orders] = await Promise.all([c.getAccountSummary(), c.getPositions(), c.getOrders()]); return { kind: "portfolio", appName: "TradePilot 212", environment: e, credentials, account, positions, orders, timestamp: new Date().toISOString() }; }
  async getTradePlan(e: TradingEnvironment, candidates: TradeCandidate[]): Promise<TradePlanPayload> { const credentials = credentialStatus(this.deps.config); if (!credentials[e]) return { kind: "trade_plan", environment: e, credentials, account: null, timestamp: new Date().toISOString(), candidates: candidates.map((x) => ({ ...x, resolutionError: `${e.toUpperCase()} credentials are not configured` })) }; const c = this.client(e); const [instruments, positions, account] = await Promise.all([this.instruments(e), c.getPositions(), c.getAccountSummary()]); const enriched: EnrichedTradeCandidate[] = candidates.map((x) => { try { const resolvedInstrument = resolveInstrumentFromList(instruments, x.ticker ?? x.symbol ?? x.name ?? ""), p = this.positionFor(positions, resolvedInstrument.ticker); return { ...x, resolvedInstrument, ...(p ? { heldQuantity: p.quantity, availableToSell: p.quantityAvailableForTrading } : {}) }; } catch (error) { return { ...x, resolutionError: error instanceof Error ? error.message : String(error) }; } }); return { kind: "trade_plan", environment: e, credentials, candidates: enriched, account, timestamp: new Date().toISOString() }; }
  private async current(draft: OrderDraft) { const instrument = resolveInstrumentFromList(await this.instruments(draft.environment), draft.ticker); draft.ticker = instrument.ticker; const c = this.client(draft.environment), [positions, account] = await Promise.all([c.getPositions(), c.getAccountSummary()]); const position = this.positionFor(positions, instrument.ticker); return { instrument, position, ...validateOrderAgainstSnapshot(draft, instrument, position, account, this.deps.config) }; }
  private async issue(value: Pending) { const token = randomToken(), expiresAt = Date.now() + this.deps.config.confirmationTtlSeconds * 1000; await this.deps.store.put(`confirm:${token}`, value, expiresAt); return { token, expiresAt: new Date(expiresAt).toISOString() }; }
  async prepareOrder(raw: OrderDraft): Promise<OrderPreview> { const draft = { ...raw, ticker: raw.ticker.trim() }; const current = await this.current(draft); const warnings: string[] = []; if (draft.environment === "live") warnings.push("LIVE: this uses real money when you confirm."); if (!current.cashCheckApplied && draft.side === "buy") warnings.push(`The instrument is priced in ${current.estimatedNotionalCurrency} while the account cash is ${current.accountCurrency ?? "another currency"}. The hard per-order cap was applied; Trading 212 remains the final funds check.`); if (draft.type === "market") warnings.push("Market orders can execute away from the reference price because of slippage."); const confirmation = await this.issue({ kind: "order", draft }); await this.deps.audit?.("order_prepared", { environment: draft.environment, ticker: draft.ticker, expiresAt: confirmation.expiresAt }); return { kind: "order_preview", ...confirmation, draft, instrument: current.instrument, estimatedNotional: current.estimatedNotional, estimatedNotionalCurrency: current.estimatedNotionalCurrency, ...(current.accountCurrency ? { accountCurrency: current.accountCurrency } : {}), ...(current.availableCash === undefined ? {} : { availableCash: current.availableCash }), ...(current.position ? { availableToSell: current.position.quantityAvailableForTrading } : {}), warnings }; }
  async executeOrder(token: string): Promise<OrderExecutionResult> { const pending = await this.deps.store.consume<Pending>(`confirm:${token}`); if (!pending || pending.kind !== "order") throw new Error("Confirmation token is invalid or expired"); const d = pending.draft; try { await this.current(d); const order = await this.client(d.environment).placeOrder(d); await this.deps.audit?.("order_submitted", { environment: d.environment, ticker: d.ticker }); return { kind: "order_execution", environment: d.environment, ok: true, status: "submitted", order, message: `${d.environment.toUpperCase()} order submitted to Trading 212` }; } catch (error) { const unknown = error instanceof ExecutionStatusUnknownError; await this.deps.audit?.(unknown ? "order_status_unknown" : "order_rejected", { environment: d.environment, ticker: d.ticker }); return { kind: "order_execution", environment: d.environment, ok: false, status: unknown ? "unknown" : "rejected", message: error instanceof Error ? error.message : String(error) }; } }
  async prepareCancel(environment: TradingEnvironment, orderId: string): Promise<CancelPreview> { const id = orderId.trim(); if (!id) throw new Error("orderId is required"); await this.client(environment).getOrder(id); return { kind: "cancel_preview", ...(await this.issue({ kind: "cancel", environment, orderId: id })), environment, orderId: id }; }
  async executeCancel(token: string): Promise<OrderExecutionResult> { const p = await this.deps.store.consume<Pending>(`confirm:${token}`); if (!p || p.kind !== "cancel") throw new Error("Confirmation token is invalid or expired"); try { const order = await this.client(p.environment).cancelOrder(p.orderId); await this.deps.audit?.("order_cancelled", { environment: p.environment, orderId: p.orderId }); return { kind: "order_execution", environment: p.environment, ok: true, status: "submitted", order, message: `${p.environment.toUpperCase()} cancel submitted` }; } catch (error) { const unknown = error instanceof ExecutionStatusUnknownError; return { kind: "order_execution", environment: p.environment, ok: false, status: unknown ? "unknown" : "rejected", message: error instanceof Error ? error.message : String(error) }; } }
}
